# Generated by Django 5.1.4 on 2025-01-03 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('description', models.TextField(default='No description required')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relationapp.author')),
            ],
        ),
    ]
